function Hd = highpass
%HIGHPASS Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.3 and DSP System Toolbox 9.5.
% Generated on: 14-Mar-2018 20:36:11

% FIR least-squares Highpass filter designed using the FIRLS function.

% All frequency values are in Hz.
Fs = 200;  % Sampling Frequency

N     = 500;  % Order
Fstop = 0.1;  % Stopband Frequency
Fpass = 0.5;  % Passband Frequency
Wstop = 1;    % Stopband Weight
Wpass = 1;    % Passband Weight

% Calculate the coefficients using the FIRLS function.
b  = firls(N, [0 Fstop Fpass Fs/2]/(Fs/2), [0 0 1 1], [Wstop Wpass]);
Hd = dfilt.dffir(b);

% [EOF]
