function [b, a] = notch
%NOTCH Returns a discrete-time filter object.
% EDITED - returns [b, a]

% MATLAB Code
% Generated by MATLAB(R) 9.3 and DSP System Toolbox 9.5.
% Generated on: 14-Mar-2018 20:34:16

% IIR Notching filter designed using the IIRNOTCH function.

% All frequency values are in Hz.
Fs = 200;  % Sampling Frequency

Fnotch = 50;  % Notch Frequency
Q      = 35;  % Q-factor
Apass  = 3;   % Bandwidth Attenuation

BW = Fnotch/Q;

% Calculate the coefficients using the IIRNOTCHPEAK function.
[b, a] = iirnotch(Fnotch/(Fs/2), BW/(Fs/2), Apass);
Hd     = dfilt.df2(b, a);

% [EOF]
